### ISSUE TITLE
Angle units other than deg aren't supported

### ISSUE THREAD

**Issue by captainbrosset** [captainbrosset/linear-gradient#5]
Try entering an angle using rad, grad or turn.

**Comment by mirceapiturca** [comment]
Modified the ANGLE_REGEX = /^-?[0-9.]+(deg|rad|grad|turn)$/; to support other units and added conversion.
A full fledged tokenizer and parser could make tooling much easier.

Made some tests and looks ok so far:
http://codepen.io/mircea/pen/MwgKaZ

**Comment by captainbrosset** [comment]
Awesome. Would you like to create a PR here with this change? Otherwise I can just take the code from your pen. Let me know.

**Comment by mirceapiturca** [comment]
Feel free to take it if you like. If not, I'll do a PR later on.
